# Site configuration

title: Suhyeon Jun
tagline: M.S. Student, CSE @ POSTECH
description: >-
  Personal page of Suhyeon Jun, M.S. student in Computer Science and Engineering at POSTECH, MLLab.

url: "https://sooh-J.github.io"
baseurl: ""

lang: en
timezone: Asia/Seoul

github:
  username: sooh-J

social:
  name: Suhyeon Jun
  email: suhyeonjun@postech.ac.kr
  links:
    - https://github.com/sooh-J
    - https://www.linkedin.com/in/sooh-j

avatar: /assets/img/profile/suhyeon_image.jpg

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Kramdown / Rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

# Files to exclude from build
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - test
  - test.c
