body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Following the guidelines can make you more likely to get responses.
      options:
        - label: >-
            I have read and accepted the
            [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).
          required: true

  - type: dropdown
    attributes:
      label: What is the topic?
      options:
        - Sharing tips and tricks
        - Just chatting
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Please describe in detail what you want to share.
    validations:
      required: true
