#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/node_modules/win-node-env/bin/CHAI_JEST_SNAPSHOT_UPDATE_ALL.js" "$@"
else 
  exec node  "$basedir/node_modules/win-node-env/bin/CHAI_JEST_SNAPSHOT_UPDATE_ALL.js" "$@"
fi
